/**
 * Generates SQL migration from products.json
 * Run: node scripts/generate_catalog_migration.js
 * Output: migrations/011_reset_catalog_and_seed.sql
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const data = JSON.parse(
  fs.readFileSync(path.join(__dirname, "..", "products.json"), "utf8"),
);

function esc(str) {
  if (!str) return "";
  return str.replace(/'/g, "''");
}

const OPTION_TYPE_MAP = {
  defaultIssuesOptions: "default_issue",
  itemsReceivedOptions: "items_received",
  additionalRequirementOptions: "additional_requirement",
  actionTakenOptions: "action_taken",
  engineerObservations: "engineer_observation",
  customerNotesOptions: "customer_note",
};

// Collect all unique brands and categories
const allBrands = new Set();
const categories = Object.keys(data);

for (const cat of categories) {
  if (!Array.isArray(data[cat])) continue;
  for (const product of data[cat]) {
    if (!product || !product.productName) continue;
    if (Array.isArray(product.brandName)) {
      for (const b of product.brandName) {
        if (b && b.trim()) allBrands.add(b.trim());
      }
    }
  }
}

let sql = "";

sql += `-- =====================================================\n`;
sql += `-- Migration: Reset catalog and seed from products.json\n`;
sql += `-- Generated by scripts/generate_catalog_migration.js\n`;
sql += `-- =====================================================\n\n`;

// 1. Clean existing data
sql += `-- 1. Clean existing dependent data first\n`;
sql += `DELETE FROM public.store_service_options;\n`;
sql += `DELETE FROM public.store_custom_brands;\n`;
sql += `DELETE FROM public.store_service_items;\n`;
sql += `DELETE FROM public.catalog_product_brands;\n`;
sql += `DELETE FROM public.catalog_brands;\n`;
sql += `DELETE FROM public.catalog_products;\n`;
sql += `DELETE FROM public.catalog_categories;\n\n`;

// 2. Create catalog_product_options table
sql += `-- 2. Create catalog_product_options table for per-product defaults\n`;
sql += `CREATE TABLE IF NOT EXISTS public.catalog_product_options (\n`;
sql += `  id serial PRIMARY KEY,\n`;
sql += `  catalog_product_id integer NOT NULL REFERENCES public.catalog_products (id) ON DELETE CASCADE,\n`;
sql += `  option_type text NOT NULL CHECK (\n`;
sql += `    option_type IN (\n`;
sql += `      'default_issue',\n`;
sql += `      'items_received',\n`;
sql += `      'action_taken',\n`;
sql += `      'engineer_observation',\n`;
sql += `      'additional_requirement',\n`;
sql += `      'customer_note'\n`;
sql += `    )\n`;
sql += `  ),\n`;
sql += `  name text NOT NULL,\n`;
sql += `  UNIQUE (catalog_product_id, option_type, name)\n`;
sql += `);\n\n`;
sql += `CREATE INDEX IF NOT EXISTS idx_catalog_product_options_product_type ON public.catalog_product_options (catalog_product_id, option_type);\n\n`;
sql += `ALTER TABLE public.catalog_product_options ENABLE ROW LEVEL SECURITY;\n`;
sql += `CREATE POLICY "Anyone can read catalog_product_options" ON public.catalog_product_options FOR SELECT USING (true);\n\n`;

// Also truncate the new table in case it already had data
sql += `DELETE FROM public.catalog_product_options;\n\n`;

// Reset sequences
sql += `-- Reset sequences\n`;
sql += `ALTER SEQUENCE IF EXISTS catalog_categories_id_seq RESTART WITH 1;\n`;
sql += `ALTER SEQUENCE IF EXISTS catalog_products_id_seq RESTART WITH 1;\n`;
sql += `ALTER SEQUENCE IF EXISTS catalog_brands_id_seq RESTART WITH 1;\n`;
sql += `ALTER SEQUENCE IF EXISTS catalog_product_options_id_seq RESTART WITH 1;\n\n`;

// 3. Insert categories
sql += `-- 3. Insert categories\n`;
sql += `INSERT INTO public.catalog_categories (name) VALUES\n`;
sql += categories.map((c) => `  ('${esc(c)}')`).join(",\n");
sql += `;\n\n`;

// 4. Insert brands
const sortedBrands = [...allBrands].sort();
sql += `-- 4. Insert brands (${sortedBrands.length} total)\n`;
sql += `INSERT INTO public.catalog_brands (name) VALUES\n`;
const brandChunks = [];
for (let i = 0; i < sortedBrands.length; i += 50) {
  brandChunks.push(sortedBrands.slice(i, i + 50));
}
sql += sortedBrands.map((b) => `  ('${esc(b)}')`).join(",\n");
sql += `;\n\n`;

// 5. Insert products and brand mappings using DO block
sql += `-- 5. Insert products, brand mappings, and default options\n`;
sql += `DO $$\n`;
sql += `DECLARE\n`;
sql += `  v_cat_id integer;\n`;
sql += `  v_prod_id integer;\n`;
sql += `  v_brand_id integer;\n`;
sql += `BEGIN\n\n`;

for (const cat of categories) {
  if (!Array.isArray(data[cat])) continue;

  sql += `  -- ========================\n`;
  sql += `  -- ${cat}\n`;
  sql += `  -- ========================\n`;
  sql += `  SELECT id INTO v_cat_id FROM public.catalog_categories WHERE name = '${esc(cat)}';\n\n`;

  for (const product of data[cat]) {
    if (!product || !product.productName) continue;

    const pName = esc(product.productName);
    sql += `  -- ${product.productName}\n`;
    sql += `  INSERT INTO public.catalog_products (category_id, name) VALUES (v_cat_id, '${pName}') ON CONFLICT (category_id, name) DO NOTHING RETURNING id INTO v_prod_id;\n`;
    sql += `  IF v_prod_id IS NULL THEN SELECT id INTO v_prod_id FROM public.catalog_products WHERE category_id = v_cat_id AND name = '${pName}'; END IF;\n`;

    // Brand mappings
    if (Array.isArray(product.brandName) && product.brandName.length > 0) {
      const brands = product.brandName
        .filter((b) => b && b.trim())
        .map((b) => `'${esc(b.trim())}'`);
      if (brands.length > 0) {
        sql += `  FOR v_brand_id IN SELECT id FROM public.catalog_brands WHERE name IN (${brands.join(",")}) LOOP\n`;
        sql += `    INSERT INTO public.catalog_product_brands (product_id, brand_id) VALUES (v_prod_id, v_brand_id) ON CONFLICT DO NOTHING;\n`;
        sql += `  END LOOP;\n`;
      }
    }

    // Option defaults
    for (const [jsonKey, dbType] of Object.entries(OPTION_TYPE_MAP)) {
      if (Array.isArray(product[jsonKey]) && product[jsonKey].length > 0) {
        const opts = product[jsonKey].filter((o) => o && o.trim());
        if (opts.length > 0) {
          sql += `  INSERT INTO public.catalog_product_options (catalog_product_id, option_type, name) VALUES\n`;
          sql += opts
            .map((o) => `    (v_prod_id, '${dbType}', '${esc(o.trim())}')`)
            .join(",\n");
          sql += `\n  ON CONFLICT DO NOTHING;\n`;
        }
      }
    }

    sql += `\n`;
  }
}

sql += `END $$;\n`;

// Write output
const outPath = path.join(
  __dirname,
  "..",
  "migrations",
  "011_reset_catalog_and_seed.sql",
);
fs.writeFileSync(outPath, sql, "utf8");

// Stats
let productCount = 0;
let optionCount = 0;
for (const cat of categories) {
  if (!Array.isArray(data[cat])) continue;
  for (const product of data[cat]) {
    if (!product || !product.productName) continue;
    productCount++;
    for (const jsonKey of Object.keys(OPTION_TYPE_MAP)) {
      if (Array.isArray(product[jsonKey])) {
        optionCount += product[jsonKey].filter((o) => o && o.trim()).length;
      }
    }
  }
}

console.log(`Generated: ${outPath}`);
console.log(
  `  Categories: ${categories.length}, Products: ${productCount}, Brands: ${sortedBrands.length}, Options: ${optionCount}`,
);
